export type Channel = {
  name: string;
  desc: string;
  logo?: string;
  category: string;
};

export const channelLogos: Record<string, string> = {
  "NRK1": "https://hime.no/wp-content/uploads/2025/02/NRK1.png",
  "NRK2": "https://hime.no/wp-content/uploads/2025/02/NRK2.png",
  "NRK3 / NRK Super": "https://hime.no/wp-content/uploads/2025/02/NRK3NRKSUper.png",
  "TV 2 Direkte": "https://hime.no/wp-content/uploads/2023/05/TV2-Direkte.png",
  "TVNorge": "https://hime.no/wp-content/uploads/2024/02/TVNorge.png",
  "TV3": "https://hime.no/wp-content/uploads/2024/11/TV3_Norway_logo_2016.svg",
  "FEM": "https://hime.no/wp-content/uploads/2024/02/FEM.png",
  "REX": "https://hime.no/wp-content/uploads/2024/03/REX.png",
  "VOX": "https://hime.no/wp-content/uploads/2024/02/Vox.png",
  "3+": "https://hime.no/wp-content/uploads/2024/11/TV3_Norway.svg",
  "TV6": "https://hime.no/wp-content/uploads/2023/05/TV6.png",
  "TV 2 Zebra": "https://hime.no/wp-content/uploads/2023/05/TV2-Zebra.png",
  "TV 2 Livsstil": "https://hime.no/wp-content/uploads/2023/05/TV2-Livsstil.png",
  "TV 2 Sport 1": "https://hime.no/wp-content/uploads/2023/05/TV2-Sport1.png",
  "TV 2 Sport 2": "https://hime.no/wp-content/uploads/2023/05/TV2-Sport-2.png",
  "TV 2 Nyheter": "https://hime.no/wp-content/uploads/2023/05/TV2-Nyheter.png",
  "VGTV": "https://hime.no/wp-content/uploads/2023/05/VGTV.png",
  "Animal Planet": "https://hime.no/wp-content/uploads/2024/02/Animal-planet.png",
  "BBC News": "https://hime.no/wp-content/uploads/2023/05/BBC-News.png",
  "Discovery Channel": "https://hime.no/wp-content/uploads/2024/02/Discovery.png",
  "Nickelodeon": "https://hime.no/wp-content/uploads/2023/05/nickelodeon.png",
  "Investigation Discovery": "https://hime.no/wp-content/uploads/2024/02/ID.png",
  "TLC": "https://hime.no/wp-content/uploads/2024/02/TLC.png",
  "Eurosport 1": "https://hime.no/wp-content/uploads/2023/05/Eurosport1.png",
  "Eurosport Norge": "https://hime.no/wp-content/uploads/2023/05/EurosportN.png",
  "SVT1": "https://hime.no/wp-content/uploads/2023/05/svt1.png",
  "SVT2": "https://hime.no/wp-content/uploads/2023/05/svt2.png",
  "TV4": "https://hime.no/wp-content/uploads/2023/05/kanal-4.png",
  "TV2 Danmark": "https://hime.no/wp-content/uploads/2023/05/tv2-danmark.png",
  "DR1": "https://hime.no/wp-content/uploads/2023/05/DR1.png",
  "DR2": "https://hime.no/wp-content/uploads/2023/05/DR2.png",
  "YLE1": "https://hime.no/wp-content/uploads/2023/05/yle-TV1.png",
  "BBC Nordic": "https://hime.no/wp-content/uploads/2023/05/BBC-Nordic.png",
  "Kunskapskanalen": "https://hime.no/wp-content/uploads/2023/05/kunnskapskanalen.png",
  "National Geographic": "https://hime.no/wp-content/uploads/2023/05/National-Geographic.png",
  "Nat Geo Wild": "https://hime.no/wp-content/uploads/2023/05/National-Geographic-Wild.png",
  "Viasat Explore": "https://hime.no/wp-content/uploads/2023/05/viasat-explore.png",
  "Viasat History": "https://hime.no/wp-content/uploads/2023/05/viasat-history.png",
  "Viasat Nature": "https://hime.no/wp-content/uploads/2023/05/Viasat-nature.png",
  "Discovery Science": "https://hime.no/wp-content/uploads/2023/05/discovery-science.png",
  "Travel Channel": "https://hime.no/wp-content/uploads/2023/05/travel-channel.png",
  "MTV": "https://hime.no/wp-content/uploads/2023/05/MTV.png",
  "Mezzo": "https://hime.no/wp-content/uploads/2023/05/mezzo.png",
  "SVT Barnkanalen": "https://hime.no/wp-content/uploads/2023/05/barnekanalen-svt24.png",
  "DR Ramasjang": "https://hime.no/wp-content/uploads/2023/05/DR-Rama-sjang.png",
  "Nick Jr.": "https://hime.no/wp-content/uploads/2023/05/nickjr.png",
  "Cartoon Network": "https://hime.no/wp-content/uploads/2023/05/cartoon-network.png",
  "CNN International": "https://hime.no/wp-content/uploads/2023/05/cnn.png",
  "CNBC": "https://hime.no/wp-content/uploads/2023/05/cnbc.png",
  "Bloomberg": "https://hime.no/wp-content/uploads/2023/05/Bloomberg.png",
  "Sky News": "https://hime.no/wp-content/uploads/2023/05/SkyNews.png",
  "Al Jazeera": "https://hime.no/wp-content/uploads/2023/05/aljazeera.png",
  "Deutsche Welle": "https://hime.no/wp-content/uploads/2023/05/deutche-welle.png",
  "France 24": "https://hime.no/wp-content/uploads/2023/05/france-24.png",
  "Das Erste": "https://hime.no/wp-content/uploads/2023/05/das-erste.png",
  "3sat": "https://hime.no/wp-content/uploads/2023/05/3sat-1.png",
  "RTL": "https://hime.no/wp-content/uploads/2023/05/RTL.png",
  "TVE International": "https://hime.no/wp-content/uploads/2023/05/Tve.png",
  "TV5 Monde": "https://hime.no/wp-content/uploads/2023/05/tv5monde.png",
  "TV Polonia": "https://hime.no/wp-content/uploads/2023/05/TVP-Polonia.png",
  "TV Visjon Norge": "https://hime.no/wp-content/uploads/2023/05/Visjon-Norge.png",
  "KANAL 10": "https://hime.no/wp-content/uploads/2023/05/kanal10norge.png",
  "Bedehuskanalen": "https://hime.no/wp-content/uploads/2023/05/bedehuskanalen.png",
};

export const baseChannels: Channel[] = [
  { name: "NRK1", desc: "Norske begivenheter, sport, nyheter og debatt", category: "Grunnpakke" },
  { name: "NRK2", desc: "Aktualitet, kultur og kunnskap", category: "Grunnpakke" },
  { name: "NRK3 / NRK Super", desc: "Underholdning og barneprogram", category: "Grunnpakke" },
  { name: "TV 2 Direkte", desc: "Norges store kommersielle kanal", category: "Grunnpakke" },
  { name: "TVNorge", desc: "Familie, serier og reality", category: "Grunnpakke" },
  { name: "TV3", desc: "Film, serier og dokumentar", category: "Grunnpakke" },
  { name: "FEM", desc: "Underholdning for moderne kvinner", category: "Grunnpakke" },
  { name: "REX", desc: "Action og sport for menn", category: "Grunnpakke" },
  { name: "VOX", desc: "Britiske serier og krim for voksne", category: "Grunnpakke" },
  { name: "3+", desc: "Maskulin underholdning og UEFA-sport", category: "Grunnpakke" },
  { name: "TV6", desc: "Livsstil for kvinner 35–49", category: "Grunnpakke" },
  { name: "TV 2 Zebra", desc: "Fotball og maskulin underholdning", category: "Grunnpakke" },
  { name: "TV 2 Livsstil", desc: "Livsstil og hverdagsmagasin", category: "Grunnpakke" },
  { name: "TV 2 Sport 1", desc: "Champions League, La Liga og internasjonal fotball", category: "Grunnpakke" },
  { name: "TV 2 Sport 2", desc: "Norsk hockey, håndball og sykling", category: "Grunnpakke" },
  { name: "TV 2 Nyheter", desc: "Norges eneste kontinuerlige nyhetskanal", category: "Grunnpakke" },
  { name: "VGTV", desc: "Nyheter og aktualitet", category: "Grunnpakke" },
  { name: "Animal Planet", desc: "Dyredokumentarer fra hele verden", category: "Grunnpakke" },
  { name: "BBC News", desc: "Globale nyheter døgnet rundt", category: "Grunnpakke" },
  { name: "Discovery Channel", desc: "Natur, historie, vitenskap og teknologi", category: "Grunnpakke" },
  { name: "Nickelodeon", desc: "Barneprogram for 2–14 år", category: "Grunnpakke" },
  { name: "Investigation Discovery", desc: "Faktabasert krim og etterforskning", category: "Grunnpakke" },
  { name: "TLC", desc: "Underholdning for kvinner 25–39", category: "Grunnpakke" },
  { name: "Eurosport 1", desc: "Tennis, sykling og golfturnering", category: "Grunnpakke" },
  { name: "Eurosport Norge", desc: "Internasjonale sportsbegivenheter", category: "Grunnpakke" },
].map(ch => ({ ...ch, logo: channelLogos[ch.name] }));

export const addonChannels: Channel[] = [
  // Nordiske
  { name: "SVT1", desc: "Svensk folkelig underholdning og nyheter", category: "Nordiske" },
  { name: "SVT2", desc: "Kultur og samfunn fra Sverige", category: "Nordiske" },
  { name: "TV4", desc: "Svensk familie-TV", category: "Nordiske" },
  { name: "TV2 Danmark", desc: "Dansk familiunderholdning", category: "Nordiske" },
  { name: "DR1", desc: "Kultur og bredt dansk programtilbud", category: "Nordiske" },
  // Dokumentar
  { name: "National Geographic", desc: "Vitenskap og utforskning", category: "Dokumentar" },
  { name: "Nat Geo Wild", desc: "Dyr og natur daglig", category: "Dokumentar" },
  { name: "Viasat Explore", desc: "Ekspedisjoner og eventyr", category: "Dokumentar" },
  // Musikk
  { name: "MTV", desc: "Musikk og underholdning for unge", category: "Musikk" },
  // Barn
  { name: "Nick Jr.", desc: "Førskoleprogrammer", category: "Barn" },
  { name: "Cartoon Network", desc: "Animasjon for alle aldre", category: "Barn" },
  // Nyheter
  { name: "CNN International", desc: "Globale nyheter 24/7", category: "Nyheter" },
  { name: "Sky News", desc: "Britiske nyheter 24 timer", category: "Nyheter" },
].map(ch => ({ ...ch, logo: channelLogos[ch.name] }));

export const allChannels = [...baseChannels, ...addonChannels];
